name: Full CI/CD
on:
  push:
    branches:
      - main
      - develop
      - test_2_coverages

jobs:
  coverage:
    name: Neorv32 coverage
    timeout-minutes: 90
    runs-on:  ubuntu-latest
    container: 
      image: ghdl/ghdl:fedora35-gcc-10.3.0
      volumes:
        - /$(pwd):/src
    steps:
      - name: Install Prerequisite
        run: |
          yum install -y python3-pip
          yum  -y install git
          yum install -y patch
          pip install gcovr 
          pip install vunit_hdl
          pip install beautifulsoup4

      - name: Git Checkout test Neorv32
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Create coverage report
        continue-on-error: true
        run: |
          patch -u ./neorv32/sim/run.py -i run.py.patch
          patch -u ./neorv32/rtl/core/neorv32_cpu.vhd -i neorv32_cpu.vhd.patch
          cd neorv32/sim
          VUNIT_SIMULATOR=ghdl ./run.py
          cd ../../
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: neorv32-code-coverage-report
          path: ./coverage.xml

  coverage_riscof:
    name: Neorv32 coverage with riscof
    timeout-minutes: 240
    runs-on:  ubuntu-latest
    container: 
      image: ghdl/ghdl:fedora35-gcc-10.3.0
      volumes:
        - /$(pwd):/src
    steps:
      - name: Install Prerequisite
        run: |
          yum install -y python3-pip
          yum  -y install git
          yum install -y patch
          yum install -y lcov
          pip install gcovr 
          pip install vunit_hdl
          pip install beautifulsoup4
          wget -nv https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
          mkdir toolchain
          tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz -C ./toolchain
          export PATH=$(pwd)/toolchain/bin:$PATH
          riscv32-unknown-elf-gcc -v

      - name: Git Checkout test Neorv32
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Git Checkout test riscof
        uses: actions/checkout@v3
        with:
          repository: stnolting/neorv32-riscof
          fetch-depth: 0
          submodules: 'false'
          path: ./riscof

      - name: Create riscof coverage report
        continue-on-error: true
        run: |
          cd riscof
          git submodule init 
          git submodule update riscv-arch-test/
          rmdir neorv32
          ln -s ../neorv32 ./
          cd ..         
          patch -u ./neorv32/sim/run.py -i run.py.patch
          patch -u ./neorv32/rtl/core/neorv32_cpu.vhd -i neorv32_cpu.vhd.patch
          patch -u ./riscof/plugin-neorv32/riscof_neorv32.py -i riscof_neorv32.py.patch
          patch -u ./riscof/sim/ghdl_setup.sh -i ghdl_setup.sh.patch
          patch -u ./riscof/sim/ghdl_run.sh -i ghdl_run.sh.patch
          cd riscof
          cd bin
          tar xvf sail-riscv.18.09.22.tar.gz 
          cd ..
          export PATH=$(pwd)/../toolchain/bin:$(pwd)/bin:$PATH
          chmod +x run.sh
          ./run.sh
          gcovr -r . --sonarqube coverage_riscof.xml
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: neorv32-riscof-code-coverage-report
          path: ./coverage_riscof.xml

  build:
    name: SonarQube Analysis
    timeout-minutes: 20
    needs: coverage
    runs-on: ubuntu-latest
    env:
      LINTY_YOSYS_PLUGIN_VERSION: 0.10.0
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Install Tabby CAD Suite
        run: |
          cd /opt
          pip install gdown
          gdown https://drive.google.com/file/d/11owYZ8XqArHr9OVEGQjtyfOEY6W-EqUZ/view?usp=sharing --fuzzy
          tar xfz tabby-linux-x64-latest.tgz
          cd tabby
          mkdir ./share/yosys/plugins
          echo "$TABBY_CAD_LICENSE" >> license.txt
        env:
          TABBY_CAD_LICENSE: ${{secrets.TABBY_CAD_LICENSE}}

      - name: Download Yosys Plugin
        uses: dsaltares/fetch-gh-release-asset@1.1.0
        with:
          repo: "Linty-Services/linty-yosys-plugin"
          version: "tags/${{env.LINTY_YOSYS_PLUGIN_VERSION}}"
          file: "linty-yosys-plugin-${{env.LINTY_YOSYS_PLUGIN_VERSION}}.tar.gz"
          target: "linty-yosys-plugin-${{env.LINTY_YOSYS_PLUGIN_VERSION}}.tar.gz"
          token: ${{ secrets.PUBLIC_SHARE_GITHUB_TOKEN }}

      - name: Install Linty Yosys Plugin
        run: tar -xvzf linty-yosys-plugin-${{env.LINTY_YOSYS_PLUGIN_VERSION}}.tar.gz -C /opt/tabby/share/yosys/plugins


      - name: Apply neorv32 patch
        run: |
          patch -u ./neorv32/sim/run.py -i run.py.patch
          patch -u ./neorv32/rtl/core/neorv32_cpu.vhd -i neorv32_cpu.vhd.patch

      - name: Download vunit coverage result
        uses: actions/download-artifact@v3
        with:
          name: neorv32-code-coverage-report

      - name: Download riscof coverage result
        uses: actions/download-artifact@v3
        with:
          name: neorv32-riscof-code-coverage-report

      - name: Run SonarQube Analysis
        run: |
          export TABBY_CAD_HOME=/opt/tabby
          export PATH="$TABBY_CAD_HOME/bin:$PATH"
          export YOSYSHQ_LICENSE=/opt/tabby/license.txt
          wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip
          unzip -q sonar-scanner-cli-4.8.0.2856.zip
          ./sonar-scanner-4.8.0.2856/bin/sonar-scanner \
            -Dsonar.host.url=https://sonar.linty-services.com \
            -Dsonar.login=${{ secrets.SONARQUBE_SCANNER_FOR_PRIVATE_REPOSITORIES_TOKEN }} \
            -Dsonar.projectKey=TEST_NEORV32 \
            -Dsonar.projectName="Test NEORV32" \
            -Dsonar.sources=./neorv32/rtl \
            -Dsonar.vhdl.topLevelEntity=neorv32_ProcessorTop_UP5KDemo \
            -Dsonar.coverageReportPaths=./coverage.xml,./coverage_riscof.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debug
          path: |
            bugfinder_workdir/
