name: Full CI/CD
on:
  push:
    branches:
      - main
      - test_cicd

jobs:
  coverage:
    runs-on:  ubuntu-latest
    needs: project_setup
    container: 
      image: ghdl/ghdl:fedora36-gcc-11.3.0
      volumes:
        - /$(pwd):/src
    steps:
      - name: Test coverage
        run: |
          pwd
          ls -al
          cd /src
          ls -al
          yum  -y install python git
          pip install gcovr 
          pip install vunit_hdl
          pip install beautifulsoup4
          git clone https://github.com/huettern/ghdl-coverage.git
          cd /src/ghdl-coverage/projects/adder/
          ghdl -a -Wc,-fprofile-arcs -Wc,-ftest-coverage adder.vhd
          ghdl -a adder_tb.vhd
          ghdl -e -Wl,-lgcov adder_tb
          ghdl -r adder_tb
          gcovr 