name: Full CI/CD
on:
  push:
    branches:
      - main
      - test_cicd

jobs:
  coverage:
    runs-on:  ubuntu-latest
    container: 
      image: ghdl/ghdl:fedora36-gcc-11.3.0
      volumes:
        - /$(pwd):/src
    steps:
      - name: Install Prerequisite
        run: |
          yum install -y python3-pip
          yum  -y install git
          pip install gcovr 
          pip install vunit_hdl
          pip install beautifulsoup4

      - name: Git Checkout test Neorv32
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Test coverage
        run: |
          pwd
          ls -al
          cd /src
          ls -al
          git clone https://github.com/huettern/ghdl-coverage.git
          cd /src/ghdl-coverage/projects/adder/
          ghdl -a -Wc,-fprofile-arcs -Wc,-ftest-coverage adder.vhd
          ghdl -a adder_tb.vhd
          ghdl -e -Wl,-lgcov adder_tb
          ghdl -r adder_tb
          gcovr 