name: Full CI/CD
on:
  push:
    branches:
      - main
      - test_cicd

jobs:
  project_setup:
    runs-on:  ubuntu-latest
    steps:
      - name: git clone
        run: |
          git clone https://github.com/huettern/ghdl-coverage.git
  coverage:
    runs-on:  ubuntu-latest
    needs: project_setup
    container: 
      image: ghdl/ghdl:fedora36-gcc-11.3.0
      volumes:
        - /$(pwd):/src
    steps:
      - name: Test coverage
        run: |
          ghdl -v
          pwd
          ls -al
          cd /src
          ls -al
          yum install python
          pip install gcovr 
          pip install vunit_hdl
          pip install beautifulsoup4