name: Update submodule

# Controls when the action will run.
on:
  push:
    branches:
       - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  #do it daily
  schedule:
    # * is a special character in YAML so you have to quote this string
    #update every day at 0:0
    - cron:  '0 0 * * *'

jobs:
  # This workflow contains a single job called "update"
  update:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Pull & update submodules recursively (not on main)
        if: github.ref != 'refs/heads/main'
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      #check if current commit is a tag
      #if not a tag answer from git describe will include 'fatal'
      - name: check new Neorv32 tag (not on main)
        if: github.ref != 'refs/heads/main'
        id: verify_tag
        run: |
          cd neorv32
          if ! git describe --exact-match --tags HEAD | grep -q 'fatal'; then   echo "newtag=true" >> $GITHUB_OUTPUT; fi
          cd ..

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit Commit & push changes to develop
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update submodules"
          git push

      - name: merge in main (if tag)
        if: steps.verify_tag.outputs.newtag == 'true'
        run: |
          git checkout main
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action tag merger"
          git merge develop
          git push